import type { TankDefinition, ContainerType } from '@/schemas/tankSchema';
import type { StoredInventoryItem } from '@/schemas/inventorySchema';
import { hybridStorage } from './hybrid-storage';

/**
 * Synchronisiert Tank-Definitionen mit dem aktuellen Inventar
 * NEUE STRATEGIE: Inventar ist die Source of Truth, manuelle Container werden hinzugefügt
 */
export async function syncTankDefinitionsWithInventory(): Promise<void> {
  if (typeof window === 'undefined') return;

  const inventoryItems: StoredInventoryItem[] = (await hybridStorage.get('inventoryItems')) || [];
  const currentTanks: TankDefinition[] = (await hybridStorage.get('tankDefinitions')) || [];
  
  console.log('🔍 Tank-Sync: Inventory Items:', inventoryItems?.length || 0);
  console.log('🔍 Tank-Sync: Aktuelle Tanks:', currentTanks?.length || 0);
  
  if (!inventoryItems || inventoryItems.length === 0) {
    console.warn('⚠️ Tank-Sync: Keine Inventory-Daten!');
    return;
  }
  
  // Gruppiere Inventar nach tankNr
  const containerData = new Map<string, {
    items: typeof inventoryItems,
    totalVolume: number,
    products: string[]
  }>();
  
  inventoryItems.forEach(item => {
    if (!item.tankNr || !item.tankNr.trim()) return;
    
    const tankNr = item.tankNr.trim();
    
    if (!containerData.has(tankNr)) {
      containerData.set(tankNr, {
        items: [],
        totalVolume: 0,
        products: []
      });
    }
    
    const data = containerData.get(tankNr)!;
    data.items.push(item);
    data.totalVolume += item.currentQuantityLiters || 0;
    if (item.produktName && !data.products.includes(item.produktName)) {
      data.products.push(item.produktName);
    }
  });
  
  // Erstelle Container aus Inventar
  const inventoryBasedContainers: TankDefinition[] = [];
  
  containerData.forEach((data, tankNr) => {
    const isUnique = tankNr.match(/^T\s?\d+/i); // Tanks mit T-Nummer
    
    if (isUnique) {
      // Eindeutige Tanks - EIN Container mit allen Produkten
      // ✅ FIX: Behalte bestehende Kapazität bei
      const existingTank = currentTanks.find(t => t.id === tankNr);
      inventoryBasedContainers.push({
        id: tankNr,
        tankNr: tankNr,
        bezeichnung: existingTank?.bezeichnung || tankNr,
        volumenLiter: existingTank?.volumenLiter || Math.max(5000, data.totalVolume * 1.2),
        containerType: 'tank',
        hasUniqueNumber: true,
        status: data.totalVolume > 0 ? 'filled' : 'empty',
        currentContent: data.products.join(', ')
      });
    } else {
      // Nicht-eindeutige Behälter (B, Fass, Fl, IBC) - Pro CHARGE ein Container
      let containerNumber = 1;
      data.items.forEach(item => {
        const containerId = `${tankNr}-${containerNumber}`;
        
        // ✅ FIX: Behalte bestehende Kapazität bei
        const existingTank = currentTanks.find(t => t.id === containerId);
        
        inventoryBasedContainers.push({
          id: containerId,
          tankNr: tankNr,
          bezeichnung: existingTank?.bezeichnung || containerId,
          volumenLiter: existingTank?.volumenLiter || Math.max(100, (item.currentQuantityLiters || 0) * 1.2),
          containerType: 'other',
          hasUniqueNumber: true, // ✅ B-1 ist eindeutig!
          currentContent: item.produktName || 'Unbekannt',
          status: (item.currentQuantityLiters || 0) > 0 ? 'filled' : 'empty'
        });
        
        containerNumber++;
      });
    }
  });
  
  console.log(`✅ ${inventoryBasedContainers.length} Container aus Inventar erstellt`);
  
  // Finde ECHTE manuell erstellte Container (nicht im Inventar)
  const inventoryIds = new Set(inventoryBasedContainers.map(c => c.id));
  const trueManualContainers = currentTanks.filter(tank => {
    // Container existiert im Inventar? → wird durch Inventar ersetzt
    if (inventoryIds.has(tank.id)) {
      return false;
    }
    
    // Container existiert NICHT im Inventar
    // Prüfe ob es ein verwaister auto-generierter Container ist
    const isOldAutoGenerated = !!tank.id.match(/^(B|Fass|Fl|IBC|T|C)\s?-?\d+$/i) &&
                                (tank.bezeichnung === tank.id || tank.bezeichnung === tank.tankNr);
    
    if (isOldAutoGenerated) {
      console.log(`🗑️ Lösche verwaisten Container: ${tank.id}`);
      return false;
    }
    
    // ECHT manuell erstellt
    console.log(`🔒 MANUELL beibehalten: ${tank.id} ("${tank.bezeichnung}")`);
    return true;
  });
  
  // Kombiniere: Inventar + manuelle Container
  const updatedTanks = [...inventoryBasedContainers, ...trueManualContainers];
  
  console.log(`📊 Total: ${updatedTanks.length} Container (${inventoryBasedContainers.length} Inventar + ${trueManualContainers.length} manuell)`);
  
  // Speichere
  await hybridStorage.set('tankDefinitions', updatedTanks);
  console.log('✅ Tank-Sync: Gespeichert');
  
  // Sync zu localStorage
  try {
    const tankData = updatedTanks.map(tank => ({
      tankNr: tank.tankNr,
      tankId: tank.tankNr,
      bezeichnung: tank.bezeichnung,
      category: tank.containerType || 'tank',
      volumenLiter: tank.volumenLiter,
      capacity: tank.volumenLiter,
      currentFill: 0,
      sorte: tank.currentContent || '',
      charge: ''
    }));
    
    localStorage.setItem('tank-data', JSON.stringify(tankData));
  } catch (error) {
    console.error('❌ localStorage sync Fehler:', error);
  }
  
  // Event
  window.dispatchEvent(new CustomEvent('tankDefinitionsUpdated', {
    detail: { tanks: updatedTanks }
  }));
}

export async function getTankDefinitions(): Promise<TankDefinition[]> {
  if (typeof window === 'undefined') return [];
  return (await hybridStorage.get('tankDefinitions')) || [];
}

export async function getTankByNumber(tankNr: string): Promise<TankDefinition | null> {
  const tanks = await getTankDefinitions();
  return tanks.find(tank => tank.tankNr === tankNr) || null;
}

export async function fixTankIds(): Promise<void> {
  if (typeof window === 'undefined') return;
  console.log('🔄 RESET: Lösche alle Tank-Definitionen...');
  await hybridStorage.set('tankDefinitions', []);
  await syncTankDefinitionsWithInventory();
}
